/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitest;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author User
 */
public class SelectProfileForm extends javax.swing.JFrame {

    
    CreateProfileForm createForm=new CreateProfileForm();
    GameLogicLayer myLogicLayer=new GameLogicLayer();
    
    String profileName=null;
    /**
     * Creates new form SelectProfileForm
     */
    public SelectProfileForm() throws SQLException {
        initComponents();
  //    DefaultComboBoxModel  nameModel = new DefaultComboBoxModel( myLogicLayer.getProfileNames());
    //  this.SelectProfileForm_List_profileNameList.setModel(nameModel);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectProfileForm_button_CreateAprofile = new javax.swing.JButton();
        SelectProfileForm_button_OK = new javax.swing.JButton();
        SelectProfileForm_Lbl_topic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SelectProfileForm_List_profileNameList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectProfileForm_button_CreateAprofile.setText("Create a New Profile");
        SelectProfileForm_button_CreateAprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProfileForm_button_CreateAprofileActionPerformed(evt);
            }
        });

        SelectProfileForm_button_OK.setText("OK");
        SelectProfileForm_button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProfileForm_button_OKActionPerformed(evt);
            }
        });

        SelectProfileForm_Lbl_topic.setText("Select Your Ptofile Here");

        SelectProfileForm_List_profileNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SelectProfileForm_List_profileNameListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(SelectProfileForm_List_profileNameList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(SelectProfileForm_button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectProfileForm_button_CreateAprofile)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(SelectProfileForm_Lbl_topic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SelectProfileForm_Lbl_topic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectProfileForm_button_CreateAprofile)
                    .addComponent(SelectProfileForm_button_OK))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    //create profile button
    private void SelectProfileForm_button_CreateAprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProfileForm_button_CreateAprofileActionPerformed
        // TODO add your handling code here:
        this.dispose();
        createForm.setVisible(true);
        createForm.setSize(500, 400);
    }//GEN-LAST:event_SelectProfileForm_button_CreateAprofileActionPerformed

    //sending the  list item selected
    private void SelectProfileForm_List_profileNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SelectProfileForm_List_profileNameListValueChanged
        // TODO add your handling code here:
        profileName=(String)SelectProfileForm_List_profileNameList.getSelectedValue();   //setting the selected profile name
        System.out.println(SelectProfileForm_List_profileNameList.getSelectedValue());
    }//GEN-LAST:event_SelectProfileForm_List_profileNameListValueChanged

    private void SelectProfileForm_button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProfileForm_button_OKActionPerformed
        // TODO add your handling code here:
        iifa myGame=new iifa(profileName);
         
         myGame.setVisible(true);
        myGame.setSize(600, 500);
        myGame.getContentPane().setBackground(Color.BLACK);
        this.dispose();
    }//GEN-LAST:event_SelectProfileForm_button_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new SelectProfileForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SelectProfileForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SelectProfileForm_Lbl_topic;
    private javax.swing.JList SelectProfileForm_List_profileNameList;
    private javax.swing.JButton SelectProfileForm_button_CreateAprofile;
    private javax.swing.JButton SelectProfileForm_button_OK;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
